### ISSUE TITLE
Odd Option Behavior

### ISSUE THREAD

**Issue by rdegges** [smurfix/flask-script#47]
I'm using Flask-Script==0.5.2 (latest stable), and am having some issues with the following command:

``` python
@manager.command
def blast(template, subject, from_addr='blah@gmail.com', from_name='Blah'):
    ...
```

This command is supposed to require a template, subject, and allow an optional from address and from name to be specified on the CLI. What happens when I run this, however, (specifying only the first two required arguments), is:

``` bash
Traceback (most recent call last):
  File "manage.py", line 334, in <module>
    manager.run()
  File "/home/rdegges/.virtualenvs/accounts/local/lib/python2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/home/rdegges/.virtualenvs/accounts/local/lib/python2.7/site-packages/flask_script/__init__.py", line 315, in handle
    command_parser = command.create_parser(prog + " " + name)
  File "/home/rdegges/.virtualenvs/accounts/local/lib/python2.7/site-packages/flask_script/commands.py", line 133, in create_parser
    parser.add_argument(*option.args, **option.kwargs)
  File "/usr/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1669, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -f/--from_addr: conflicting option string(s): -f
```

I've tried specifying the arguments numerous ways, eg:

``` bash
$ python manage.py blast 'template' 'subject'
$ python manage.py blast --template='template' --subject='subject'
$ python manage.py blast 'template' 'subject' 'from_addr' 'from_name'
```

However, regardless of how I specify the options, I get the same error.

**Comment by ei-grad** [comment]
![facepalm](http://news-front.info/wp-content/uploads/2015/09/Facepalm_iWKad22.jpg)
